image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker-compose -f docker-compose.yml build
    - docker-compose -f docker-compose.yml push

deploy:
  stage: deploy
  script:
    - ssh benchamkha@62.169.24.84 "docker pull $IMAGE_TAG"
    - ssh benchamkha@62.169.24.84 "docker-compose -f ./docker-compose.yml up -d"
  only:
    - main
