services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"
    networks:
      - backend

  server:
    build:  
      context: ./server
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - "8000:8000"
    networks:
      - backend

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "3050:80"
    depends_on:
      - client
      - server
    networks:
      - backend

networks:
  backend:
    driver: bridge